import React, { useState } from 'react';
import { Calendar, MapPin, Share2, Download, Eye } from 'lucide-react';
import { useApp } from '../contexts/AppContext';

const IncidentList = () => {
  const { state } = useApp();
  const [selectedIncident, setSelectedIncident] = useState(null);

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleString();
  };

  const handleShare = (incident) => {
    const shareData = {
      title: 'Guardian Guide Incident Report',
      text: `Incident recorded on ${formatDate(incident.timestamp)}`,
      url: window.location.href
    };

    if (navigator.share) {
      navigator.share(shareData);
    } else {
      // Fallback - copy to clipboard
      navigator.clipboard.writeText(
        `Incident Report\nDate: ${formatDate(incident.timestamp)}\nLocation: ${incident.location?.name || 'Unknown'}\nSummary: ${incident.summary}`
      );
      alert('Incident details copied to clipboard!');
    }
  };

  const generateSummary = (incident) => {
    return `Incident Report

Date/Time: ${formatDate(incident.timestamp)}
Location: ${incident.location?.name || 'Unknown location'}
Type: ${incident.interactionType.replace('_', ' ').toUpperCase()}
Duration: ${incident.duration ? `${Math.floor(incident.duration / 60)}:${(incident.duration % 60).toString().padStart(2, '0')}` : 'N/A'}
Recording: ${incident.recordingUrl || 'None'}

Summary: ${incident.summary}

Generated by Guardian Guide
Your pocket rights advisor`;
  };

  if (state.incidents.length === 0) {
    return (
      <div className="bg-surface rounded-lg shadow-card p-8 text-center">
        <h3 className="text-lg font-semibold text-text-primary mb-2">No Incidents Recorded</h3>
        <p className="text-text-secondary">
          Your recorded interactions will appear here. Use the Quick Record feature to document any encounters.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <h3 className="text-lg font-semibold text-text-primary">Recent Incidents</h3>
      
      {state.incidents.map((incident) => (
        <div key={incident.reportId} className="bg-surface rounded-lg shadow-card p-4">
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <div className="flex items-center space-x-2 mb-2">
                <Calendar className="h-4 w-4 text-text-secondary" />
                <span className="text-sm text-text-secondary">
                  {formatDate(incident.timestamp)}
                </span>
              </div>
              
              {incident.location && (
                <div className="flex items-center space-x-2 mb-2">
                  <MapPin className="h-4 w-4 text-text-secondary" />
                  <span className="text-sm text-text-secondary">
                    {incident.location.name}
                  </span>
                </div>
              )}
              
              <p className="text-text-primary font-medium mb-2">{incident.summary}</p>
              
              {incident.recordingUrl && (
                <div className="flex items-center space-x-2 mb-3">
                  <div className={`w-2 h-2 rounded-full ${incident.type === 'video' ? 'bg-blue-500' : 'bg-accent'}`}></div>
                  <span className="text-xs text-text-secondary">
                    {incident.type === 'video' ? 'Video' : 'Audio'} recording available
                  </span>
                </div>
              )}
            </div>
            
            <div className="flex space-x-2">
              <button
                onClick={() => setSelectedIncident(incident)}
                className="p-2 hover:bg-gray-100 rounded-md"
                title="View Details"
              >
                <Eye className="h-4 w-4" />
              </button>
              <button
                onClick={() => handleShare(incident)}
                className="p-2 hover:bg-gray-100 rounded-md"
                title="Share"
              >
                <Share2 className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>
      ))}

      {/* Incident Detail Modal */}
      {selectedIncident && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-surface rounded-lg max-w-2xl w-full max-h-[80vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xl font-semibold text-text-primary">Incident Details</h3>
                <button
                  onClick={() => setSelectedIncident(null)}
                  className="p-2 hover:bg-gray-100 rounded-md"
                >
                  ×
                </button>
              </div>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">
                    Date & Time
                  </label>
                  <p className="text-text-primary">{formatDate(selectedIncident.timestamp)}</p>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">
                    Location
                  </label>
                  <p className="text-text-primary">{selectedIncident.location?.name || 'Unknown'}</p>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">
                    Summary
                  </label>
                  <p className="text-text-primary">{selectedIncident.summary}</p>
                </div>
                
                {selectedIncident.recordingUrl && (
                  <div>
                    <label className="block text-sm font-medium text-text-secondary mb-1">
                      Recording
                    </label>
                    <div className="flex items-center space-x-2 p-3 bg-gray-50 rounded-md">
                      <div className={`w-3 h-3 rounded-full ${selectedIncident.type === 'video' ? 'bg-blue-500' : 'bg-accent'}`}></div>
                      <span className="text-sm">{selectedIncident.recordingUrl}</span>
                    </div>
                  </div>
                )}
                
                <div className="pt-4 border-t">
                  <h4 className="font-medium text-text-primary mb-2">Shareable Summary</h4>
                  <pre className="text-xs bg-gray-50 p-3 rounded-md whitespace-pre-wrap text-text-secondary">
                    {generateSummary(selectedIncident)}
                  </pre>
                </div>
              </div>
              
              <div className="flex space-x-3 mt-6 pt-4 border-t">
                <button
                  onClick={() => handleShare(selectedIncident)}
                  className="flex-1 bg-primary text-white py-2 px-4 rounded-md hover:bg-blue-600 transition-colors"
                >
                  Share Report
                </button>
                <button
                  onClick={() => {
                    const element = document.createElement('a');
                    const file = new Blob([generateSummary(selectedIncident)], { type: 'text/plain' });
                    element.href = URL.createObjectURL(file);
                    element.download = `incident_${selectedIncident.reportId}.txt`;
                    document.body.appendChild(element);
                    element.click();
                    document.body.removeChild(element);
                  }}
                  className="flex items-center space-x-2 border border-gray-300 py-2 px-4 rounded-md hover:bg-gray-50 transition-colors"
                >
                  <Download className="h-4 w-4" />
                  <span>Download</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default IncidentList;